"""Claude (Anthropic) LLM provider with prompt caching.

Caching Strategy:
    Claude supports the most flexible caching via inline cache_control markers.
    Unlike Gemini/OpenAI, Claude can cache specific blocks within the system prompt,
    allowing both static and dynamic content to stay in the system prompt.

    How it works:
    - System prompt is an array of content blocks
    - Each block can have its own cache_control setting
    - Blocks with cache_control={"type": "ephemeral"} are cached
    - Blocks without cache_control are NOT cached but still processed normally

    What we cache:
    - Static prompt (instructions, profile): cached with ephemeral marker
    - Tools (last tool marked): cached with ephemeral marker
    - Dynamic context (recent meals, alerts): NOT cached, no marker

    Cache TTL Options:
    - 5 minutes (default): cache_control={"type": "ephemeral"}
    - 1 hour: cache_control={"type": "ephemeral", "ttl": "1h"}

    Set TTL via constructor: ClaudeProvider(cache_ttl="1h")

    Cost Savings:
    - cache_read_input_tokens: 90% cheaper than regular input tokens
    - cache_creation_input_tokens: 25% more expensive (one-time cost)
    - 1-hour cache has slightly higher storage cost than 5-minute cache

Usage Reporting (already matches normalized format):
    - input_tokens: tokens NOT from cache (dynamic context + user message)
    - output_tokens: tokens generated by the model
    - cache_creation_input_tokens: tokens written to cache (first request)
    - cache_read_input_tokens: tokens read from cache (subsequent requests)

    Total input = input_tokens + cache_creation_input_tokens (or cache_read_input_tokens)

Note on server.py:
    The web streaming in server.py uses the Anthropic client directly rather than
    this provider class. This is because the streaming API requires different
    handling for SSE events. The caching logic there mirrors _prepare_cached_request().
"""

import os
from typing import Generator

import anthropic

from .base import BaseLLMProvider, LLMResponse


class ClaudeProvider(BaseLLMProvider):
    """Anthropic Claude provider with prompt caching support.

    Supports both legacy single-string system prompts and the preferred
    tuple format (static_prompt, dynamic_context) for proper cache separation.
    """
    
    # Valid cache TTL values
    CACHE_TTL_5MIN = None  # Default 5-minute ephemeral cache (no ttl field needed)
    CACHE_TTL_1HOUR = "1h"  # Extended 1-hour cache (slightly higher cost)

    def __init__(self, model: str = "claude-haiku-4-5-20251001", api_key: str = None, cache_ttl: str = None):
        """Initialize Claude provider.

        Args:
            model: Model name (default: claude-haiku-4-5-20251001)
            api_key: Anthropic API key (default: from ANTHROPIC_API_KEY env var)
            cache_ttl: Cache TTL - None for 5 minutes (default), "1h" for 1 hour.
                      If not passed, reads from CLAUDE_CACHE_TTL env var.
        """
        self.model = model
        self.client = anthropic.Anthropic(api_key=api_key or os.getenv("ANTHROPIC_API_KEY"))
        # Use passed value, or env var, or default to None (5 min)
        self.cache_ttl = cache_ttl if cache_ttl is not None else os.getenv("CLAUDE_CACHE_TTL")

    def _prepare_cached_request(
        self,
        system_prompt: str | tuple[str, str],
        tools: list
    ) -> tuple[list, list]:
        """
        Prepare system prompt and tools with cache_control markers.

        Args:
            system_prompt: Either a single string (legacy, entire prompt cached) or
                          a tuple of (static_prompt, dynamic_context) where only
                          static_prompt is cached.
            tools: List of tool definitions in Anthropic format.

        Returns:
            Tuple of (cached_system, cached_tools) ready for the API.

        Caching behavior:
            - Static prompt block: cache_control=ephemeral (cached for configured TTL)
            - Dynamic context block: no cache_control (not cached)
            - Last tool: cache_control=ephemeral (caches entire tool list)

        Why cache only the last tool?
            Claude caches everything up to and including a cache_control marker.
            By marking only the last tool, we cache all tools efficiently with
            a single marker.
        """
        # Build cache_control dict based on TTL setting
        # None = 5-minute default, "1h" = 1-hour extended cache
        if self.cache_ttl:
            cache_control = {"type": "ephemeral", "ttl": self.cache_ttl}
        else:
            cache_control = {"type": "ephemeral"}

        # Handle both legacy single-string and new split format
        if isinstance(system_prompt, tuple):
            static_prompt, dynamic_context = system_prompt
            cached_system = [
                {
                    "type": "text",
                    "text": static_prompt,
                    "cache_control": cache_control
                },
                {
                    "type": "text",
                    "text": dynamic_context
                    # No cache_control — this changes each call
                }
            ]
        else:
            # Legacy: single string, cache the whole thing
            cached_system = [
                {
                    "type": "text",
                    "text": system_prompt,
                    "cache_control": cache_control
                }
            ]

        # Mark the last tool for caching (caches all tools)
        cached_tools = tools.copy()
        if cached_tools:
            cached_tools[-1] = {
                **cached_tools[-1],
                "cache_control": cache_control
            }

        return cached_system, cached_tools

    def chat(
        self,
        messages: list,
        system_prompt: str,
        tools: list,
        max_tokens: int = 4096,
    ) -> LLMResponse:
        """Send a chat request to Claude with prompt caching."""
        cached_system, cached_tools = self._prepare_cached_request(system_prompt, tools)

        response = self.client.messages.create(
            model=self.model,
            max_tokens=max_tokens,
            system=cached_system,
            tools=cached_tools,
            messages=messages,
        )
        
        # Extract usage information
        usage = None
        if hasattr(response, 'usage'):
            usage = {
                "input_tokens": getattr(response.usage, 'input_tokens', 0),
                "output_tokens": getattr(response.usage, 'output_tokens', 0),
                "cache_creation_input_tokens": getattr(response.usage, 'cache_creation_input_tokens', 0),
                "cache_read_input_tokens": getattr(response.usage, 'cache_read_input_tokens', 0),
            }

        # Convert to standard format
        content = []
        for block in response.content:
            if block.type == "text":
                content.append({"type": "text", "text": block.text})
            elif block.type == "tool_use":
                content.append({
                    "type": "tool_use",
                    "id": block.id,
                    "name": block.name,
                    "input": block.input,
                })
        
        return LLMResponse(content=content, stop_reason=response.stop_reason, usage=usage)
    
    def chat_stream(
        self,
        messages: list,
        system_prompt: str,
        tools: list,
        max_tokens: int = 4096,
    ) -> Generator[dict, None, LLMResponse]:
        """Stream a chat response from Claude with prompt caching."""
        cached_system, cached_tools = self._prepare_cached_request(system_prompt, tools)

        with self.client.messages.stream(
            model=self.model,
            max_tokens=max_tokens,
            system=cached_system,
            tools=cached_tools,
            messages=messages,
        ) as stream:
            for event in stream:
                if event.type == "content_block_start":
                    if event.content_block.type == "text":
                        pass  # Text will come in deltas
                    elif event.content_block.type == "tool_use":
                        yield {"type": "tool_start", "name": event.content_block.name, "id": event.content_block.id}
                
                elif event.type == "content_block_delta":
                    if event.delta.type == "text_delta":
                        yield {"type": "text", "content": event.delta.text}
                    elif event.delta.type == "input_json_delta":
                        yield {"type": "tool_input", "content": event.delta.partial_json}
            
            # Get final message
            final_message = stream.get_final_message()
            
            # Extract usage information
            usage = None
            if hasattr(final_message, 'usage'):
                usage = {
                    "input_tokens": getattr(final_message.usage, 'input_tokens', 0),
                    "output_tokens": getattr(final_message.usage, 'output_tokens', 0),
                    "cache_creation_input_tokens": getattr(final_message.usage, 'cache_creation_input_tokens', 0),
                    "cache_read_input_tokens": getattr(final_message.usage, 'cache_read_input_tokens', 0),
                }

            # Convert to standard format
            content = []
            for block in final_message.content:
                if block.type == "text":
                    content.append({"type": "text", "text": block.text})
                elif block.type == "tool_use":
                    content.append({
                        "type": "tool_use",
                        "id": block.id,
                        "name": block.name,
                        "input": block.input,
                    })
            
            return LLMResponse(content=content, stop_reason=final_message.stop_reason, usage=usage)
    
    def get_model_name(self) -> str:
        return self.model
