"""Google Gemini LLM provider using the new google-genai SDK.

Caching Strategy:
    Gemini uses explicit caching via client.caches.create(). Unlike Claude's
    inline cache_control markers, Gemini caches the entire system_instruction
    as a single unit. This means:

    1. We can only cache content that doesn't change between requests
    2. Dynamic context (recent meals, alerts) must be moved to user messages
    3. The server.py handles this by passing only static_prompt to system_instruction

    Cache Management:
    - Caches are stored in _gemini_cache_store (module-level dict)
    - Key: hash of model + system_prompt
    - Value: {"name": cache_name, "expires_at": timestamp}
    - TTL: 1 hour (Gemini minimum is 60 minutes)
    - Expired caches are deleted and recreated on next request

    Cost Savings:
    - Gemini 2.5+: 90% discount on cached input tokens
    - Gemini 2.0: 75% discount on cached input tokens
    - Storage cost: based on TTL duration

Usage Reporting (normalized to match Claude's semantics):
    Gemini's API returns:
    - prompt_token_count: TOTAL input tokens (cached + uncached)
    - cached_content_token_count: tokens read from cache
    - candidates_token_count: output tokens

    We normalize to match Claude's API response:
    - input_tokens: uncached input only (prompt_token_count - cached_content_token_count)
    - cache_creation_input_tokens: tokens written to cache (when cache is created)
    - cache_read_input_tokens: tokens read from cache (subsequent requests)
    - output_tokens: tokens generated by the model

    Total input = input_tokens + cache_creation_input_tokens (or cache_read_input_tokens)
"""

import hashlib
import json
import os
import time
from typing import Generator, Optional

from .base import BaseLLMProvider, LLMResponse


# Module-level cache storage for Gemini context caching
# Persists across requests within the same process (not across restarts)
# Key: hash of (model, system_prompt), Value: {"name": cache_name, "expires_at": timestamp}
_gemini_cache_store: dict[str, dict] = {}


class GeminiProvider(BaseLLMProvider):
    """Google Gemini provider using the new unified SDK."""
    
    # Minimum token count for caching (Gemini 2.5: 2048, Gemini 3: 4096)
    # GutAgent's system prompt is ~6k tokens, so caching should work
    MIN_CACHE_TOKENS = 2048

    # Cache TTL in seconds (minimum 60 minutes for Gemini)
    CACHE_TTL_SECONDS = 3600  # 1 hour

    def __init__(self, model: str = "gemini-2.5-flash", api_key: str = None, enable_caching: bool = True):
        self.model = model
        self.enable_caching = enable_caching

        try:
            from google import genai
            from google.genai import types
        except ImportError:
            raise ImportError("google-genai package not installed. Run: pip install google-genai")
        
        # Get API key
        api_key = api_key or os.getenv("GEMINI_API_KEY")
        if not api_key:
            raise ValueError("No API key found. Set GEMINI_API_KEY environment variable.")
        
        self.client = genai.Client(api_key=api_key)
        self.types = types
    
    def _get_cache_key(self, system_prompt: str) -> str:
        """Generate a cache key from model and system prompt."""
        content = f"{self.model}:{system_prompt}"
        return hashlib.sha256(content.encode()).hexdigest()[:16]

    def _get_or_create_cache(self, system_prompt: str, tools: list) -> tuple[Optional[str], int]:
        """Get existing cache or create new one for the system prompt.

        Returns:
            Tuple of (cache_name, cache_creation_tokens):
            - cache_name: The cache name if caching is available, None otherwise
            - cache_creation_tokens: Number of tokens written to cache (0 if cache hit or no cache)
        """
        if not self.enable_caching:
            return None, 0

        cache_key = self._get_cache_key(system_prompt)
        now = time.time()

        # Check if we have a valid cached entry
        if cache_key in _gemini_cache_store:
            entry = _gemini_cache_store[cache_key]
            if entry["expires_at"] > now:
                return entry["name"], 0  # Cache hit, no creation tokens
            else:
                # Cache expired, remove it
                try:
                    self.client.caches.delete(name=entry["name"])
                except Exception:
                    pass  # Ignore deletion errors
                del _gemini_cache_store[cache_key]

        # Create new cache
        try:
            # Build cache config with system instruction and tools
            cache_config = {
                "system_instruction": system_prompt,
                "ttl": f"{self.CACHE_TTL_SECONDS}s",
                "display_name": f"gutagent-{cache_key}",
            }

            # Add tools to cache if present
            if tools:
                gemini_tools = self._convert_tools_to_gemini(tools)
                cache_config["tools"] = [self.types.Tool(function_declarations=gemini_tools)]

            cache = self.client.caches.create(
                model=self.model,
                config=self.types.CreateCachedContentConfig(**cache_config),
            )

            # Get token count from cache creation
            cache_tokens = 0
            if hasattr(cache, 'usage_metadata') and cache.usage_metadata:
                cache_tokens = getattr(cache.usage_metadata, 'total_token_count', 0) or 0

            # Store cache reference
            _gemini_cache_store[cache_key] = {
                "name": cache.name,
                "expires_at": now + self.CACHE_TTL_SECONDS - 60,  # Buffer for safety
            }

            return cache.name, cache_tokens

        except Exception:
            # Caching might fail for various reasons (model not supported, prompt too small, etc.)
            # Fall back to non-cached request silently
            return None, 0

    def _convert_tools_to_gemini(self, tools: list) -> list:
        """Convert Anthropic tool format to Gemini function declarations."""
        gemini_tools = []
        for tool in tools:
            gemini_tools.append(
                self.types.FunctionDeclaration(
                    name=tool["name"],
                    description=tool.get("description", ""),
                    parameters=tool.get("input_schema", {}),
                )
            )
        return gemini_tools
    
    def _convert_messages_to_gemini(self, messages: list) -> list:
        """Convert Anthropic message format to Gemini contents."""
        contents = []
        
        for msg in messages:
            role = msg["role"]
            content = msg["content"]
            
            # Gemini uses "user" and "model" roles
            gemini_role = "model" if role == "assistant" else "user"
            
            if role == "user":
                if isinstance(content, list) and content and content[0].get("type") == "tool_result":
                    # Tool results
                    parts = []
                    for tool_result in content:
                        parts.append(
                            self.types.Part.from_function_response(
                                name=tool_result.get("tool_name", "unknown"),
                                response={"result": tool_result["content"]}
                            )
                        )
                    contents.append(self.types.Content(role="user", parts=parts))
                else:
                    text = content if isinstance(content, str) else json.dumps(content)
                    contents.append(self.types.Content(role="user", parts=[self.types.Part.from_text(text=text)]))
            
            elif role == "assistant":
                if isinstance(content, str):
                    contents.append(self.types.Content(role="model", parts=[self.types.Part.from_text(text=content)]))
                elif isinstance(content, list):
                    parts = []
                    for block in content:
                        if block.get("type") == "tool_use":
                            parts.append(
                                self.types.Part.from_function_call(
                                    name=block["name"],
                                    args=block["input"],
                                )
                            )
                        elif block.get("type") == "text" and block.get("text"):
                            parts.append(self.types.Part.from_text(text=block["text"]))
                    if parts:
                        contents.append(self.types.Content(role="model", parts=parts))
        
        return contents
    
    def chat(
        self,
        messages: list,
        system_prompt: str,
        tools: list,
        max_tokens: int = 4096,
    ) -> LLMResponse:
        """Send a chat request to Gemini."""
        gemini_tools = self._convert_tools_to_gemini(tools) if tools else None
        contents = self._convert_messages_to_gemini(messages)
        
        # Try to get or create cache for system prompt
        cache_name, cache_creation_tokens = self._get_or_create_cache(system_prompt, tools)

        # Build config
        config_kwargs = {
            "max_output_tokens": max_tokens,
        }

        if cache_name:
            # Use cached content - don't include system_instruction or tools (they're in cache)
            config_kwargs["cached_content"] = cache_name
        else:
            # No cache - include system instruction and tools directly
            config_kwargs["system_instruction"] = system_prompt
            if gemini_tools:
                config_kwargs["tools"] = [self.types.Tool(function_declarations=gemini_tools)]
                config_kwargs["automatic_function_calling"] = self.types.AutomaticFunctionCallingConfig(disable=True)
        
        config = self.types.GenerateContentConfig(**config_kwargs)
        
        response = self.client.models.generate_content(
            model=self.model,
            contents=contents,
            config=config,
        )
        
        # Convert response to standard format
        content = []
        has_tool_calls = False
        
        if response.candidates and response.candidates[0].content:
            parts = response.candidates[0].content.parts
            if parts:  # parts can be None
                for part in parts:
                    if hasattr(part, 'text') and part.text:
                        content.append({"type": "text", "text": part.text})
                    elif hasattr(part, 'function_call') and part.function_call:
                        has_tool_calls = True
                        fc = part.function_call
                        # Convert args to dict
                        args = dict(fc.args) if fc.args else {}
                        content.append({
                            "type": "tool_use",
                            "id": f"tool_{fc.name}",
                            "name": fc.name,
                            "input": args,
                        })
        
        # If no content, provide a fallback message
        if not content:
            content.append({"type": "text", "text": "[No response from model]"})

        stop_reason = "tool_use" if has_tool_calls else "end_turn"

        # Extract token usage if available
        # Match Claude's semantics:
        # - input_tokens: tokens NOT from cache (dynamic context + user message)
        # - cache_creation_input_tokens: tokens written to cache (first request)
        # - cache_read_input_tokens: tokens read from cache (subsequent requests)
        # - output_tokens: tokens generated by the model
        usage = None
        if hasattr(response, 'usage_metadata') and response.usage_metadata:
            um = response.usage_metadata
            total_input = getattr(um, 'prompt_token_count', 0) or 0
            cached_tokens = getattr(um, 'cached_content_token_count', 0) or 0

            # input_tokens = total - cached (to match Claude's semantics)
            uncached_input = total_input - cached_tokens

            usage = {
                "input_tokens": uncached_input,
                "output_tokens": getattr(um, 'candidates_token_count', 0) or 0,
            }

            # Report cache_creation OR cache_read, not both
            if cache_creation_tokens > 0:
                usage["cache_creation_input_tokens"] = cache_creation_tokens
            elif cached_tokens > 0:
                usage["cache_read_input_tokens"] = cached_tokens

        return LLMResponse(content=content, stop_reason=stop_reason, usage=usage)
    
    def chat_stream(
        self,
        messages: list,
        system_prompt: str,
        tools: list,
        max_tokens: int = 4096,
    ) -> Generator[dict, None, LLMResponse]:
        """Stream a chat response from Gemini with true streaming support."""
        gemini_tools = self._convert_tools_to_gemini(tools) if tools else None
        contents = self._convert_messages_to_gemini(messages)

        # Try to get or create cache for system prompt
        cache_name, cache_creation_tokens = self._get_or_create_cache(system_prompt, tools)

        # Build config
        config_kwargs = {
            "max_output_tokens": max_tokens,
        }

        if cache_name:
            # Use cached content
            config_kwargs["cached_content"] = cache_name
        else:
            # No cache - include system instruction and tools directly
            config_kwargs["system_instruction"] = system_prompt
            if gemini_tools:
                config_kwargs["tools"] = [self.types.Tool(function_declarations=gemini_tools)]
                config_kwargs["automatic_function_calling"] = self.types.AutomaticFunctionCallingConfig(disable=True)

        config = self.types.GenerateContentConfig(**config_kwargs)

        # Use streaming API
        stream = self.client.models.generate_content_stream(
            model=self.model,
            contents=contents,
            config=config,
        )

        # Collect content as we stream
        collected_text = ""
        collected_tool_calls = []
        usage = None

        for chunk in stream:
            # Extract usage from final chunk
            # Match Claude's semantics: input_tokens = uncached only
            if hasattr(chunk, 'usage_metadata') and chunk.usage_metadata:
                um = chunk.usage_metadata
                total_input = getattr(um, 'prompt_token_count', 0) or 0
                cached_tokens = getattr(um, 'cached_content_token_count', 0) or 0
                uncached_input = total_input - cached_tokens

                usage = {
                    "input_tokens": uncached_input,
                    "output_tokens": getattr(um, 'candidates_token_count', 0) or 0,
                }
                # Report cache_creation OR cache_read, not both
                if cache_creation_tokens > 0:
                    usage["cache_creation_input_tokens"] = cache_creation_tokens
                elif cached_tokens > 0:
                    usage["cache_read_input_tokens"] = cached_tokens

            if not chunk.candidates or not chunk.candidates[0].content:
                continue

            parts = chunk.candidates[0].content.parts
            if not parts:
                continue

            for part in parts:
                if hasattr(part, 'text') and part.text:
                    collected_text += part.text
                    yield {"type": "text", "content": part.text}
                elif hasattr(part, 'function_call') and part.function_call:
                    fc = part.function_call
                    args = dict(fc.args) if fc.args else {}
                    tool_call = {
                        "type": "tool_use",
                        "id": f"tool_{fc.name}",
                        "name": fc.name,
                        "input": args,
                    }
                    collected_tool_calls.append(tool_call)
                    yield {"type": "tool_start", "name": fc.name, "id": tool_call["id"]}
        
        # Build final response
        content = []
        if collected_text:
            content.append({"type": "text", "text": collected_text})
        content.extend(collected_tool_calls)

        if not content:
            content.append({"type": "text", "text": "[No response from model]"})
        
        stop_reason = "tool_use" if collected_tool_calls else "end_turn"

        return LLMResponse(content=content, stop_reason=stop_reason, usage=usage)
    
    def get_model_name(self) -> str:
        return f"gemini/{self.model}"
